replicaCount: 3

metadata:
 name: angular 
 label: angular

image:
  name: angular
  imageName: "icpdevcluster.icp:8500/default/angular:latest" 
  imagePullPolicy: IfNotPresent

service:
  serviceMetadata:
    name: angular
  selector:
    selectorName: angular
  servicePortConfiguration:
    name: angular
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30090