apiVersion: v1
kind: Service
metadata:
 name: bookingsvc
 labels:
   app: bookingsvc
spec:
 type: NodePort
 selector:
   app: bookingsvc
 ports:
  - protocol: TCP
    name: bookingsvc
    port: 3000
    targetPort: 3000
    nodePort: 30090