# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

metadata:
 name: bookingsvc 
 label: bookingsvc

image:
  name: bookingsvc
  image: "icpdevcluster.icp:8500/default/booking-microservice:latest" 
  imagePullPolicy: IfNotPresent
  ports:
    containerPort: 3000

envOfSecrets:
  envUID:
    name: UID
    secretKeyRef:
      name: mysecret
      key: UID
  envPASSWORD:
    name: PASSWORD
    secretKeyRef:
      name: mysecret
      key: PASSWORD
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envNODE_ENV:
    name: NODE_ENV
    configMapKeyRef:
      name: env-database
      key: NODE_ENV
  envDATABASE:
    name: DATABASE
    configMapKeyRef:
      name: env-database
      key: DATABASE
  envPORT:
    name: PORT
    configMapKeyRef:
      name: env-database
      key: PORT
  envHOSTNAME:
    name: HOSTNAME
    configMapKeyRef:
      name: env-database
      key: HOSTNAME
  envPROTOCOL:
    name: PROTOCOL
    configMapKeyRef:
      name: env-database
      key: PROTOCOL


service:
  serviceMetadata:
    name: bookingsvc
    labels:
    app: bookingsvc
  selector:
    selectorName: bookingsvc
  servicePortConfiguration:
    protocol: TCP
    name: bookingsvc
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30090