apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: db2svc 
spec:
 replicas: 1
 template:
   metadata:
     name: db2svc
     labels:
       app: db2svc
   spec:
     containers:
       - name: db2svcluster
         image: "registry.eu-gb.bluemix.net/icpairways/db2:latest"
         imagePullPolicy: Always
         env:
            - name: DB2INST1_PASSWORD
              value: .7475443aA!
            - name: LICENSE
              value: accept
        #  volumeMounts:
        #   - name: db2-storage
        #     mountPath: /home/db2inst1/
         ports:
          - containerPort: 50000
    #  volumes:
    #   - name: db2-storage
    #     persistentVolumeClaim:
    #       claimName: db2-pv-claim
---
apiVersion: v1
kind: Service
metadata:
 name: db2svc 
 labels:
   app: db2svc
spec:
 type: ClusterIP
 selector:
   app: db2svc
 ports:
  - protocol: TCP
    name: db2svc
    port: 50000
    targetPort: 50000
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db2-pv-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: db2-pv-claim
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"