apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: icp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: icp.example.com
    http:
      paths:
      - path: /listingsvc
        backend:
          serviceName: listingsvc
          servicePort: 3002
