---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared
  labels:
    type: local
    name: shared
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 172.16.164.222
    path: "/data/storage1"
  accessModes:
    - ReadWriteMany
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: shared
  persistentVolumeReclaimPolicy: Retain