apiVersion: v1
kind: ConfigMap
metadata:
  name: env-database
  namespace: default
data:
  NODE_ENV: development
  DATABASE: SAMPLE
  PORT: '30662'
  HOSTNAME: '169.61.62.89'
  PROTOCOL: TCPIP
  ODM: 'http://169.61.62.89:32473/DecisionService/rest/FlightBooking/FlightPricing'