apiVersion: v1
kind: ConfigMap
metadata:
  name: env-database
  namespace: default
data:
  NODE_ENV: development
  DATABASE: SAMPLE
  PORT: '50000'
  HOSTNAME: db2svc.svc.cluster.local
  PROTOCOL: TCPIP