apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: default
data:
  login: http://loginsvc.svc.cluster.local/login
  signup: http://signupsvc.svc.cluster.local/createUser
  book: http://bookingsvc.svc.cluster.local/book
  listBookingByUser: http://bookingsvc.svc.cluster.local/listBookingByUser
  checkin: http://checkinsvc.svc.cluster.local/checkin
  listFlightsByID: http://listingsvc.svc.cluster.local/listFlightsByID
  listFlights: http://listingsvc.svc.cluster.local/listFlights