apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ethereumproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ethereumproxy
    spec:
      containers:
        - name: ethereumproxy
          image: "mycluster.icp:8500/default/ethereumproxy:latest"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ethereumproxy
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
  selector:
    app: ethereumproxy