apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }} 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.label }} 
    spec:
      containers:
        - name: {{ .Values.metadata.name }} 
          image: {{ .Values.image.imageName }} 
          imagePullPolicy: {{ .Values.image.imagePullPolicy }} 